name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  simple_job:
    name: Run Simple Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print current directory
        run: pwd

      - name: List files in repository
        run: ls -a
