name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Set up environment variables
        run: |
          echo "HOST=${{ env.HOST }}" >> .env
          echo "TOKEN=${{ env.TOKEN }}" >> .env
          echo "T_MAX=${{ env.T_MAX }}" >> .env
          echo "T_MIN=${{ env.T_MIN }}" >> .env
          echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env
          echo "MIN_CONN=${{ env.MIN_CONN }}" >> .env
          echo "MAX_CONN=${{ env.MAX_CONN }}" >> .env

      - name: Run tests
        run: pipenv run test
